# Generated by Django 4.2.2 on 2023-08-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemcode", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=50)),
                ("barcode", models.CharField(max_length=20)),
                ("unitmeasure", models.CharField(max_length=5)),
                ("inventory", models.IntegerField()),
                (
                    "unitcost",
                    models.DecimalField(decimal_places=2, max_digits=10000000000),
                ),
            ],
        ),
    ]
