# Generated by Django 4.2.2 on 2023-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erpapp", "0002_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
    ]
