# Generated by Django 4.2.2 on 2023-08-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erpapp", "0003_items_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/%Y"),
        ),
    ]
